# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5f77f2a399de379a1360150905e12f3086d3055adf1218efd2f7db466ecf7d7ff9b1cb4272fc0505a96112631e88c09602e5e805b991e2e679222c834d3b121

test:
  secret_key_base: ec6e9b75401a39f73fafb271a2846fb93b9bfac21b1aee58008cd48d02ce0df59033ba1fb5c3e3e427be35435dc8f4fa46f317bf17e3673ac8b90b015c33cb3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
